spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
  artemis:
    host: localhost
    port: 8161
    user: matt
    password: matt
  jms:
    template:
      default-destination: tacocloud.order.queue

password: l3tm31n
logging:
  level:
    root: INFO
    org.springframework: INFO
    sia.taco_cloud: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'