spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    sia.taco_cloud: DEBUG